### ISSUE TITLE
Is there a way to send options when subscribe?

### ISSUE THREAD

**Issue by jiajun-ifanr** [konsultaner/connectanum-dart#17] opened 2020-10-30 07:47 UTC
In line 27 of `example/main.dart`, it demonstrates an example of how to subscribe to a topic:

```dart
final subscription = await session.subscribe(topic);
```

But what about sending options when subscribe?

I want to pass a Map like `{"a": 123}` as an option to the server as it is required.

Is there a way to do this?

I see that there is a second parameter `SubscribeOptions` that has three variables: `match`, `meta_topic` and `get_retained`, but have no idea what they are.

**Comment by konsultaner** [comment] 2020-10-30 09:09
The `SubscribeOptions` are used to support WAMP advanced fatures like [Pattern Based Subscription](https://wamp-proto.org/_static/gen/wamp_latest.html#pattern-based-subscriptions) . This is where you need the `match` option.

Since dart does not support a reflection api, I hard coded all SubscribeOptions that I knew exists.

What are the information you want to share during the subscription process? What is the router you use? What advanced feature do you want to use that is not supported by this package?

**Comment by jiajun-ifanr** [comment] 2020-10-30 10:04
I have an issue when passing an options (or even without one) on subscribe.

Say for example I have the following code in my `main.dart`, (without a `SubscribeOptions` passed):

```dart
import 'package:flutter/material.dart';
import 'package:connectanum/connectanum.dart';
import 'package:connectanum/json.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  void initState() {
    super.initState();
    test();
  }

  void test() async {
    WampImplementation wamp = new WampImplementation();
    wamp.subscribe();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Test App'),
      ),
    );
  }
}

class WampImplementation {
  Client client;

  void subscribe() async {
    String url =
        'wss://a4d2d62965ddb57fa4d6.ws.myminapp.com/ws/hydrogen/?x-hydrogen-client-id=a4d2d62965ddb57fa4d6&x-hydrogen-env-id=f1eeb28c9552d4c83df1&authorization=Hydrogen-r1%20580co4jlkysw7rprsgz4edxx9pubot3s';

    client = Client(
      realm: 'com.ifanrcloud',
      transport: WebSocketTransport(
        url,
        new Serializer(),
        WebSocketSerialization.SERIALIZATION_JSON,
      ),
    );

    Session session;

    try {
      session = await client.connect().first;
      String topic = 'com.ifanrcloud.schema_event.danmu_jiajun.on_create';

      // SubscribeOptions options = new SubscribeOptions();
      final subscription = await session.subscribe(topic);
      // subscription.eventStream.listen((event) => print(event.arguments[0]));
    } on Abort catch (abort) {
      print(abort.message.message);
    }
  }
}

```

When the above code executes, there are two errors shown:
1. Unhandled Exception: Bad state: No element
2. Unhandled Exception: NoSuchMethodError: The getter 'inMilliseconds' was called on null.

I can't figure out what had happened here with the above errors. Kinda strange.

**Comment by konsultaner** [comment] 2020-10-30 16:10
> However, even when I execute the below code without an option, there are two errors shown:
> 
> 1. Unhandled Exception: Bad state: No element
> 2. Unhandled Exception: NoSuchMethodError: The getter 'inMilliseconds' was called on null.

The exception 1 is thrown because the socket is closed by the router before the subscribe receives the subscription.

I don't get why exception is thrown, because there is a nullpointer check.. weired. I can't reproduce number 2 with my code.
 
```
[
        32,
        912873614,
        {
            "where": {}
        },
        "com.myapp.topic.emergency"
]
```

This is not possible at the moment. I could implement it.

**Comment by jiajun-ifanr** [comment] 2020-10-31 02:38
Many thanks. 

But how did you know about the cause of exception 1? Is it possible to debug WebSocket via the package or could you recommend any methods (like Charles) to debug by myself? I've searched for answers with no hope for quite some time now.

Also, is it possible to throw an error message with better explanation about the exception rather than `Bad state: No element` since it might be confusing and I at first thought it was a Flutter issue.

**Comment by konsultaner** [comment] 2020-10-31 12:44
@jiajun-ifanr I wrote a little unit test based on you code:

```dart
import 'package:connectanum/connectanum.dart';
import 'package:connectanum/json.dart';
import 'package:test/test.dart';

void main() {
  test("error", () async {
    await WampImplementation.subscribe();
  });
}

class WampImplementation {
  static void subscribe() async {
    String url =
        'wss://a4d2d62965ddb57fa4d6.ws.myminapp.com/ws/hydrogen/?x-hydrogen-client-id=a4d2d62965ddb57fa4d6&x-hydrogen-env-id=f1eeb28c9552d4c83df1&authorization=Hydrogen-r1%20580co4jlkysw7rprsgz4edxx9pubot3s';

    Client client = Client(
      realm: 'com.ifanrcloud',
      transport: WebSocketTransport(
        url,
        new Serializer(),
        WebSocketSerialization.SERIALIZATION_JSON,
      ),
    );

    Session session;

    try {
      session = await client.connect().first;
      String topic = 'com.ifanrcloud.schema_event.danmu_jiajun.on_create';

      // SubscribeOptions options = new SubscribeOptions();
      final subscription = await session.subscribe(topic);
      // subscription.eventStream.listen((event) => print(event.arguments[0]));
    } on Abort catch (abort) {
      print(abort.message.message);
    }
  }
}
```

You need to know that this package uses the transport streams and wraps a broadcast stream pre session around it. This way the broadcast stream may be closed safely and may be listened to multiple times.

https://github.com/konsultaner/connectanum-dart/blob/322a483c96acc841018dc63410dbfd0e48f557cf/lib/src/protocol/session.dart#L130

You will see the transport stream is closed before the `subscribe` can receive a `subscribed` here:

https://github.com/konsultaner/connectanum-dart/blob/322a483c96acc841018dc63410dbfd0e48f557cf/lib/src/protocol/session.dart#L225

This is not really an error but rather an event. You may have to subscribe to those events:

https://github.com/konsultaner/connectanum-dart/blob/322a483c96acc841018dc63410dbfd0e48f557cf/lib/src/transport/websocket/websocket_transport_io.dart#L45

**Comment by konsultaner** [comment] 2020-10-31 13:27
@jiajun-ifanr I have tried some code where you can so something like this

```dart
var options = new SubscribeOptions();
options.addCustomValue("where", (serializerType) => "{}");
final subscription = await session.subscribe(topic, options: options);
```

This makes it possible to pass a custom field with a custom serializer for either msgpack or json to a subscribe option. I tried it with your code an the server responded with a subscribed as expected. I will publish the code soon. I just need to write some tests and add the custom options to all the other message types as well.

**Closed** 2020-10-31 14:30 UTC
Labels: enhancement, waiting-for-user-reply

**Comment by konsultaner** [comment] 2020-10-31 14:31
I only added custom options for subscriptions for now. If you need it for registrations too, plz open a new issue

**Comment by jiajun-ifanr** [comment] 2020-10-31 15:40
Thanks a lot for your help!

I can now successfully subscribe to a topic and receive responses from our server.

But I still can't print out what the server has responded since the `event.arguments` (or anything in `event`) is always `null`:

```dart
subscription.eventStream.listen((event) => print(event.arguments[0]));
```

It is believed that the server has sent valid information to a client (my JS client does receive it correctly) but I will have it checked with my colleagues.

I really appreciate your help. In what way I can buy you a cup of coffee?

**Comment by konsultaner** [comment] 2020-11-02 07:00
> But I still can't print out what the server has responded since the event.arguments (or anything in event) is always null:

I'll check that in a minute.

> I really appreciate your help. In what way I can buy you a cup of coffee?

Never mind! 😄 A ⭐ is enough

**Comment by konsultaner** [comment] 2020-11-02 08:37
@jiajun-ifanr I cannot debug it anymore, I get this error: `Permission denied, please call login function first.`

**Comment by jiajun-ifanr** [comment] 2020-11-02 09:35
@konsultaner Please try and update the `wss` url with the following:

```dart
String url =
        'wss://a4d2d62965ddb57fa4d6.ws.myminapp.com/ws/hydrogen/?x-hydrogen-client-id=a4d2d62965ddb57fa4d6&x-hydrogen-env-id=f1eeb28c9552d4c83df1&authorization=Hydrogen-r1%20qlnol4csq38uzsne04wzd6y3684g1yy4';
```

`event.arguments` might only be printed out when the server responds. If you need me to send a response to the client, please let me know.

**Comment by konsultaner** [comment] 2020-11-02 09:39
Could you send a respond every 1000ms?

**Comment by jiajun-ifanr** [comment] 2020-11-02 09:55
@konsultaner Yes, now I send one every 3000ms

**Comment by konsultaner** [comment] 2020-11-02 09:59
Your server has a wrong message encoding, the null values are wrong:

```json
[36,844427229501,null,{},null,{"after":{"text":"this is example text","_read_perm":["user:anonymous"],"_write_perm":[],"created_at":1604311031,"updated_at":1604311031,"created_by":236097344815877,"id":"5f9fd7f7e9ed7d7681c837b4"},"before":{},"event":"on_create","schema_id":107144,"schema_name":"danmu_jiajun","id":"5f9fd7f7e9ed7d7681c837b4"}]
```

**Comment by konsultaner** [comment] 2020-11-02 10:04
sorry. I see this should still work

**Comment by konsultaner** [comment] 2020-11-02 10:07
@jiajun-ifanr The issue is that you printing args but argKwds. 

```dart
print(event.argumentsKeywords);
```

this works

**Comment by jiajun-ifanr** [comment] 2020-11-02 10:28
@konsultaner  Perfect! I can now get it work.

Thank you for all your support and kindness throughout the entire problem-solving process.

**Comment by konsultaner** [comment] 2020-11-02 10:46
@jiajun-ifanr I'm very eger to make this module work as good as possible. I have not used it in production but I will soon. So having people to test it for me is just perfekt. So you helped me too. 😅
