### ISSUE TITLE
Client close required to close unauthorised session on reconnect!

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#6] opened 2020-03-10 13:22 UTC
I was connecting to Client without `authid` and `ticket`. After some time i was doing reconnect with authid. But it didn't worked. And it is because, i already have anonymous client session open. Wamp doesn't understand how to change between anonymous session to authorised, without session close. So for my project session.close() is crucial.

**Comment by konsultaner** [comment] 2020-03-10 14:17
I don't quite understand. In WAMP there is one session per authentication process. Could you specify your issue?

**Comment by konsultaner** [comment] 2020-03-10 14:19
look at this: https://wamp-proto.org/_static/gen/wamp_latest.html#transport-and-session-lifetime

**Comment by andzejsw** [comment] 2020-03-10 14:20
I am authorised with anonymous user. Basically without `authid` and without `ticket`. I am using sms login to authorise. After sms is received, i want to close anonymous session and start new, with authid, which i received from server.

**Comment by konsultaner** [comment] 2020-03-10 14:22
For this you should implement your own 2 factor authentication. Ticket is not suitable for this. I still don't get what the issue is, sorry.

**Comment by andzejsw** [comment] 2020-03-10 14:24
Ticket auth works for me in `Jawampa`. I can't create new authorised session, till i close unauthorised one.

**Comment by konsultaner** [comment] 2020-03-10 14:25
So you want to have 2 sessions in parallel?

**Comment by andzejsw** [comment] 2020-03-10 14:25
Nope. I want to close first one and then open new, which one has authid.

**Comment by konsultaner** [comment] 2020-03-10 14:30
like this ?:

```dart
final client1 = Client(
  realm: "my.realm",
  transport: WebSocketTransport(
    "ws://localhost:8080/wamp",
    new Serializer(),
    WebSocketSerialization.SERIALIZATION_JSON
  ),
  authenticationMethods: [TicketAuthentication("")]
);
final session1 = await client1.connect();

final client2 = Client(
  realm: "my.realm",
  authId: "user"
  transport: WebSocketTransport(
    "ws://localhost:8080/wamp",
    new Serializer(),
    WebSocketSerialization.SERIALIZATION_JSON
  ),
  authenticationMethods: [TicketAuthentication("password")]
);
final session2 = await client2.connect();
```

**Comment by andzejsw** [comment] 2020-03-10 14:31
Before i create second session, i want to close first session. But there is no session close. That is the issue for me.

**Comment by andzejsw** [comment] 2020-03-10 14:36
> like this ?:
> 
> ```dart
> final client1 = Client(
>   realm: "my.realm",
>   transport: WebSocketTransport(
>     "ws://localhost:8080/wamp",
>     new Serializer(),
>     WebSocketSerialization.SERIALIZATION_JSON
>   ),
>   authenticationMethods: [TicketAuthentication("")]
> );
> final session1 = await client1.connect();
> 
> final client2 = Client(
>   realm: "my.realm",
>   authId: "user"
>   transport: WebSocketTransport(
>     "ws://localhost:8080/wamp",
>     new Serializer(),
>     WebSocketSerialization.SERIALIZATION_JSON
>   ),
>   authenticationMethods: [TicketAuthentication("password")]
> );
> final session2 = await client2.connect();
> ```

these looks parallel sessions, if i am not mistaking. Nope. I want one at a time.  Like:

```
final client = Client(
  realm: "my.realm",
  transport: WebSocketTransport(
    "ws://localhost:8080/wamp",
    new Serializer(),
    WebSocketSerialization.SERIALIZATION_JSON
  ),
);
final session = await client.connect();
```
then i receive sms and call `reconnect` method:
```
  void reconnect(String uuid) {
    disconnect(); // Close first unauthorised client
    connectWampClient(uuid); // TODO: start client with specific uuid
  }
```
In `disconnect` method i close session
  void disconnect() {
    session.close(); // TODO: Close client
    session = null;
  }
In `connectWampClient` i create new client and session: 
```
    Client client = Client(
      realm: "my.realm",
      transport: WebSocketTransport(
          "wss://wsUrl.lv/cws",
          new Serializer(),
          WebSocketSerialization.SERIALIZATION_JSON
      ),
      authId: authId,
      authenticationMethods: authId == null ? null : [TicketAuthentication(authId)],
    );

    session = await client.connect();
```

**Comment by konsultaner** [comment] 2020-03-10 14:37
I'm aout to add the close method. Meanwhile you may just close the transport.

**Comment by andzejsw** [comment] 2020-03-10 14:39
> I'm aout to add the close method. Meanwhile you may just close the transport.
I tried to add following code in `session.dart`, but it didn't worked:
```
  Future<void> close() async {
    return await _transport.close();
  }
```

**Comment by konsultaner** [comment] 2020-03-10 14:42
I'm up to something like this:

```dart
Future<void> close({String message = "Regular closing", Duration timeout}) {
    final goodbye = Goodbye(
        GoodbyeMessage(message),
        Goodbye.REASON_GOODBYE_AND_OUT);
    this._transport.send(goodbye);
    if (timeout != null) {
      return Future.delayed(timeout, () => this._transport.close());
    }
    return Future.value();
  }
```

the server should return a goodbye and close the transport.

**Comment by andzejsw** [comment] 2020-03-10 14:45
Ok. Please inform me or close issue, when it is finished! :)

**Comment by konsultaner** [comment] 2020-03-10 14:50
I added the code. you try?

**Comment by konsultaner** [comment] 2020-03-10 14:53
by the way, isnt that wrong?:

```dart
/// don't you mean TicketAuthentication(password) <-----
authenticationMethods: authId == null ? null : [TicketAuthentication(authId)]
```

**Comment by andzejsw** [comment] 2020-03-10 14:57
It isn't wrong. In my case authid and ticket password matches.
PS: Looks like that you didn't pushed these changes in master.

**Comment by konsultaner** [comment] 2020-03-10 14:57
sry i have 2 repos. try now

**Comment by andzejsw** [comment] 2020-03-10 15:00
Hmm. Code is pushed. But not working for me.

**Comment by konsultaner** [comment] 2020-03-10 15:03
is it not connecting or what is the issue?

**Comment by andzejsw** [comment] 2020-03-10 15:05
It isn't connecting second client, which was created after first close.

**Comment by andzejsw** [comment] 2020-03-10 15:06
Other dev, with whoom i am working told me previously, that i am sending correctly wamp authorisation, but couldn't authorise, cause there was already session connected. Most likely same thing remains and close isn't working compitely.

**Comment by konsultaner** [comment] 2020-03-10 15:12
The transport is [definitly closed when](https://github.com/konsultaner/connectanum-dart/blob/master/test/client_test.dart#L116) calling.

```dart
session.close(timestamp: Duration(milliseconds:1))
```

 The unit test is green. Sure this is an issue of this package?

**Comment by andzejsw** [comment] 2020-03-10 15:13
Ok. I will test everything deeper and return here, if i find something more.

**Comment by konsultaner** [comment] 2020-03-10 15:15
I had similar issues one day. It was related to a transparent closing the tcp connection. sending a ping pong under the hood helped. Dart itself does [not seem to support it](https://github.com/dart-lang/sdk/issues/36728) atm.

**Comment by andzejsw** [comment] 2020-03-11 08:44
I just tested Client connect by directly providing authid (previously i tested by switching from unauthorised session to authorised) for authorised session and i can't connect to server. Could it be, that TicketAuthentication method isn't working!?

**Comment by konsultaner** [comment] 2020-03-11 08:50
I have a separate test for that. I'll give it a try with an integration test.

**Comment by konsultaner** [comment] 2020-03-11 09:06
I added the test and it works as expected. very strange... Is the client event connecting to the server?
I tried the simple auth process with the connectanum router, but I havn't tried cra or ticket yet. I'll give it a try later today. could you debug the authprocess with your router? what is your router?

**Comment by andzejsw** [comment] 2020-03-11 09:14
With unauthorised client everything is fine. But when i use ticket, it doesn't work. From server side we see, that no one tried to connect with specified authid. So server doesn't receive it. I will try to connect to web and see if i can connect with the same authid using autobahn.

**Comment by andzejsw** [comment] 2020-03-11 09:44
With autobahn i can successfully login using ticket.

**Comment by konsultaner** [comment] 2020-03-11 09:59
I have never used this package in production, just test driven development ;) I'll write a running example later and test it with a router. What is the name of your router?

**Comment by andzejsw** [comment] 2020-03-11 10:01
I am using Crossbar.io.

**Comment by konsultaner** [comment] 2020-03-11 10:07
right

**Comment by konsultaner** [comment] 2020-03-11 11:17
please try again!

**Comment by andzejsw** [comment] 2020-03-11 11:20
Wow nice! Now it works!

**Comment by andzejsw** [comment] 2020-03-11 11:22
I thin that issue can be closed. Cause now i tested full flow and it worked!

**Comment by konsultaner** [comment] 2020-03-11 11:27
perfect!

**Closed by konsultaner** 2020-03-11 11:27 UTC
Labels: waiting-for-user-reply
